name: Update User Stats

on:
  schedule:
    - cron: "0 17 * * *" #run every at 17:00:00s UTC / 00.00 GMT +7 / 01.00 GMT +8

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests
      - name: Execute Script
        run: |
          python main.py
      - name: Commit File
        run: |
          git config --local user.email "81743021+mzakiyuddin@users.noreply.github.com"
          git config --local user.name "mzakiyuddin"
          git add .
          now=$(date)
          git commit -m "Update $now"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
